// Date: 2015/03/03 21:13:20
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package jp.koushin_lawfirm.www.entity;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelAtsushi extends ModelBase {
	// fields
	ModelRenderer LLeg;
	ModelRenderer RLeg;
	ModelRenderer LFoot;
	ModelRenderer RFoot;
	ModelRenderer Body;
	ModelRenderer Neck;
	ModelRenderer Head;
	ModelRenderer Lip;

	public ModelAtsushi() {
		textureWidth = 64;
		textureHeight = 32;

		LLeg = new ModelRenderer(this, 48, 0);
		LLeg.addBox(0F, 0F, 0F, 1, 14, 1);
		LLeg.setRotationPoint(3F, 10F, 0F);
		LLeg.setTextureSize(64, 32);
		LLeg.mirror = true;
		setRotation(LLeg, 0F, 0F, 0F);
		RLeg = new ModelRenderer(this, 48, 0);
		RLeg.addBox(0F, 0F, 0F, 1, 14, 1);
		RLeg.setRotationPoint(-4F, 10F, 0F);
		RLeg.setTextureSize(64, 32);
		RLeg.mirror = true;
		setRotation(RLeg, 0F, 0F, 0F);
		LFoot = new ModelRenderer(this, 18, 27);
		LFoot.addBox(0F, 13F, -4F, 3, 1, 4);
		LFoot.setRotationPoint(3F, 10F, 1F);
		LFoot.setTextureSize(64, 32);
		LFoot.mirror = true;
		setRotation(LFoot, 0F, 0F, 0F);
		RFoot = new ModelRenderer(this, 18, 27);
		RFoot.addBox(-3F, 13F, -4F, 3, 1, 4);
		RFoot.setRotationPoint(-3F, 10F, 1F);
		RFoot.setTextureSize(64, 32);
		RFoot.mirror = true;
		setRotation(RFoot, 0F, 0F, 0F);
		Body = new ModelRenderer(this, 16, 0);
		Body.addBox(0F, 0F, 0F, 8, 8, 16);
		Body.setRotationPoint(-4F, 2F, -8F);
		Body.setTextureSize(64, 32);
		Body.mirror = true;
		setRotation(Body, 0F, 0F, 0F);
		Neck = new ModelRenderer(this, 8, 0);
		Neck.addBox(0F, 0F, 0F, 2, 11, 2);
		Neck.setRotationPoint(-1F, -9F, -7F);
		Neck.setTextureSize(64, 32);
		Neck.mirror = true;
		setRotation(Neck, 0F, 0F, 0F);
		Head = new ModelRenderer(this, 0, 24);
		Head.addBox(0F, 0F, 0F, 4, 3, 5);
		Head.setRotationPoint(-2F, -12F, -9F);
		Head.setTextureSize(64, 32);
		Head.mirror = true;
		setRotation(Head, 0F, 0F, 0F);
		Lip = new ModelRenderer(this, 32, 30);
		Lip.addBox(0F, 0F, 0F, 4, 1, 1);
		Lip.setRotationPoint(-2F, -10F, -10F);
		Lip.setTextureSize(64, 32);
		Lip.mirror = true;
		setRotation(Lip, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		if (this.isChild) {
			float f6 = 2.0F;
			GL11.glPopMatrix();
			GL11.glPushMatrix();
			GL11.glScalef(1.0F / f6, 1.0F / f6, 1.0F / f6);
			GL11.glTranslatef(0.0F, 24.0F * f5, 0.0F);
			this.RLeg.render(f5);
			this.LLeg.render(f5);
			GL11.glPopMatrix();
			GL11.glPushMatrix();
			GL11.glScalef(1.0F / f6, 1.0F / f6, 1.0F / f6);
			GL11.glTranslatef(0.0F, 24.0F * f5, 0.0F);
			this.RFoot.render(f5);
			this.LFoot.render(f5);
			GL11.glPopMatrix();
		} else {
			LLeg.render(f5);
			RLeg.render(f5);
			LFoot.render(f5);
			RFoot.render(f5);
			Body.render(f5);
			Neck.render(f5);
			Head.render(f5);
			Lip.render(f5);
		}
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.RLeg.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
		this.LLeg.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI)
				* 1.4F * f1;
		this.RFoot.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
		this.LFoot.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI)
				* 1.4F * f1;


	}

}
